/**
 * Sign-up choices for the web version: the SAME organization list and
 * countries as the plugin's download form (UN-OCHA/dataviz_download_BDU,
 * index.html), so sign-ups and downloads can be counted together.
 * Copied on 8 Oct 2026 — if the download form's lists change, copy them here
 * too (the dashboard groups organizations by the acronym before the dash).
 */
/* exported SIGNUP_LISTS */
var SIGNUP_LISTS = {
 "organizations": [
  "UNDP — United Nations Development Programme",
  "UNCDF — UN Capital Development Fund",
  "UNV — United Nations Volunteers",
  "UNEP — UN Environment Programme",
  "UNFPA — United Nations Population Fund",
  "UN-Habitat — UN Human Settlements Programme",
  "UNICEF — United Nations Children&#x27;s Fund",
  "WFP — World Food Programme",
  "UNHCR — UN Refugee Agency",
  "UNOPS — UN Office for Project Services",
  "UNRWA — UN Relief and Works Agency for Palestine Refugees",
  "UN-Women — UN Entity for Gender Equality and the Empowerment of Women",
  "FAO — Food and Agriculture Organization",
  "ICAO — International Civil Aviation Organization",
  "IFAD — International Fund for Agricultural Development",
  "ILO — International Labour Organization",
  "IMF — International Monetary Fund",
  "IMO — International Maritime Organization",
  "ITU — International Telecommunication Union",
  "UNESCO — UN Educational, Scientific and Cultural Organization",
  "UNIDO — UN Industrial Development Organization",
  "UN Tourism — World Tourism Organization",
  "UPU — Universal Postal Union",
  "WHO — World Health Organization",
  "WIPO — World Intellectual Property Organization",
  "WMO — World Meteorological Organization",
  "World Bank — World Bank Group",
  "IBRD — International Bank for Reconstruction and Development",
  "IDA — International Development Association",
  "IFC — International Finance Corporation",
  "IAEA — International Atomic Energy Agency",
  "ICC — International Criminal Court",
  "IOM — International Organization for Migration",
  "ISA — International Seabed Authority",
  "ITLOS — International Tribunal for the Law of the Sea",
  "OPCW — Organisation for the Prohibition of Chemical Weapons",
  "WTO — World Trade Organization",
  "CTBTO — Comprehensive Nuclear-Test-Ban Treaty Organization",
  "OCHA — Office for the Coordination of Humanitarian Affairs",
  "DPO — Department of Peace Operations",
  "DPPA — Department of Political and Peacebuilding Affairs",
  "DSS — Department of Safety and Security",
  "DESA — Department of Economic and Social Affairs",
  "DGACM — Dept for General Assembly and Conference Management",
  "DGC — Department of Global Communications",
  "DMSPC — Dept of Management Strategy, Policy and Compliance",
  "DOS — Department of Operational Support",
  "DCO — Development Coordination Office",
  "EOSG — Executive Office of the Secretary-General",
  "OHCHR — UN Human Rights (OHCHR)",
  "OIOS — Office of Internal Oversight Services",
  "OLA — Office of Legal Affairs",
  "OCT — Office of Counter-Terrorism",
  "ODA — Office for Disarmament Affairs",
  "ODET — Office for Digital and Emerging Technologies",
  "OOSA — Office for Outer Space Affairs",
  "OSAA — Office of the Special Adviser on Africa",
  "UNDRR — UN Office for Disaster Risk Reduction",
  "UNODC — UN Office on Drugs and Crime",
  "UNOG — United Nations Office at Geneva",
  "UNON — United Nations Office at Nairobi",
  "UNOV — United Nations Office at Vienna",
  "UN-OHRLLS — Office of the High Rep. for LDCs, LLDCs and SIDS",
  "ITC — International Trade Centre",
  "UNCTAD — UN Conference on Trade and Development",
  "UNAIDS — Joint UN Programme on HIV/AIDS",
  "UNU — United Nations University",
  "UNITAR — UN Institute for Training and Research",
  "UNIDIR — UN Institute for Disarmament Research",
  "UNSSC — UN System Staff College",
  "UNICRI — UN Interregional Crime and Justice Research Institute",
  "UNRISD — UN Research Institute for Social Development",
  "ECA — Economic Commission for Africa",
  "ECE — Economic Commission for Europe",
  "ECLAC — Economic Commission for Latin America and the Caribbean",
  "ESCAP — Economic and Social Commission for Asia and the Pacific",
  "ESCWA — Economic and Social Commission for Western Asia"
 ],
 "countries": [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo (DR of the)",
  "Costa Rica",
  "Cote d&#x27;Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (DPR of)",
  "Korea (Republic of)",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Lao PDR",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "State of Palestine",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkiye",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
 ]
};
